import os
from typing import Dict, Any, List, Optional
from agents.security.tools import SecurityTools
from agents.security.prompts import SECURITY_SYSTEM_PROMPT

class SecurityAgent:
    """
    Security Agent: Performs automated static security audits, detects exposed secrets,
    verifies dependency hygiene, and produces actionable security reports before PR creation.
    """

    def __init__(self, root_dir: str):
        self.root_dir = os.path.abspath(root_dir)
        self.tools = SecurityTools(self.root_dir)

    def scan_changes(self, changes: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Scans modified code chunks and unified diffs generated by the Coder Agent.
        """
        raw_findings = []
        scanned_files = []

        for change in changes:
            file_path = change.get("file_path", "")
            new_content = change.get("new_content", "")
            diff = change.get("diff", "")
            
            scanned_files.append(file_path)
            content_to_scan = new_content if new_content else diff
            if content_to_scan:
                findings = self.tools.scan_content(file_path, content_to_scan)
                raw_findings.extend(findings)

        return self._build_security_report(raw_findings, scanned_files)

    def scan_repository(self, rel_paths: Optional[List[str]] = None) -> Dict[str, Any]:
        """
        Audits selected workspace files or typical source files across the project.
        """
        target_files = rel_paths or [
            "apps/web/src/app/login/page.tsx",
            "apps/api/main.py",
            "agents/coder/agent.py",
            "sandbox/runner/container_runner.py"
        ]

        raw_findings = []
        scanned_files = []

        for file_path in target_files:
            scanned_files.append(file_path)
            findings = self.tools.scan_file(file_path)
            raw_findings.extend(findings)

        return self._build_security_report(raw_findings, scanned_files)

    def _build_security_report(self, raw_findings: List[Dict[str, Any]], scanned_files: List[str]) -> Dict[str, Any]:
        """
        Aggregates, deduplicates, and calculates the security health score.
        """
        # Deduplicate findings by (file, line, rule_id)
        seen = set()
        deduped = []
        for f in raw_findings:
            key = (f.get("file"), f.get("line"), f.get("rule_id"))
            if key not in seen:
                seen.add(key)
                deduped.append(f)

        critical_count = sum(1 for f in deduped if f.get("severity") == "CRITICAL")
        high_count = sum(1 for f in deduped if f.get("severity") == "HIGH")
        medium_count = sum(1 for f in deduped if f.get("severity") == "MEDIUM")
        low_count = sum(1 for f in deduped if f.get("severity") == "LOW")

        # Security Score formula (100 base)
        penalty = (critical_count * 30) + (high_count * 15) + (medium_count * 5) + (low_count * 2)
        security_score = max(0, 100 - penalty)

        passed = critical_count == 0 and high_count == 0

        status = "PASSED" if passed else "BLOCKED_BY_POLICY"
        grade = "A" if security_score >= 90 else ("B" if security_score >= 75 else ("C" if security_score >= 60 else "F"))

        return {
            "status": status,
            "passed": passed,
            "security_score": security_score,
            "grade": grade,
            "scanned_files_count": len(scanned_files),
            "scanned_files": scanned_files,
            "total_findings_count": len(deduped),
            "severity_summary": {
                "critical": critical_count,
                "high": high_count,
                "medium": medium_count,
                "low": low_count
            },
            "findings": deduped,
            "approval_gate": {
                "merge_allowed": passed,
                "reason": "Clean scan, zero critical/high findings" if passed else "Critical or High severity findings must be resolved prior to merge."
            }
        }
