import os
from typing import Dict, Any, List
from agents.coder.tools import CoderTools

class CoderAgent:
    """
    Coder Agent: Performs controlled code modifications based on the Planner Agent's output
    and produces unified diffs for human developer review and approval.
    """

    def __init__(self, root_dir: str):
        self.root_dir = root_dir
        self.tools = CoderTools(root_dir)

    def execute_modification(self, plan: Dict[str, Any]) -> Dict[str, Any]:
        task_request = plan.get("task_request", "Update software functionality")
        affected_files_detailed = plan.get("affected_files_detailed", [])
        
        if affected_files_detailed:
            target_files = [f["path"] for f in affected_files_detailed]
        else:
            target_files = plan.get("affected_files", ["apps/web/src/app/login/page.tsx", "apps/api/main.py"])

        changes = []
        total_additions = 0
        total_deletions = 0

        for rel_path in target_files[:3]:
            existing_content = self.tools.read_file(rel_path)
            is_new = existing_content.startswith("Error") or not existing_content.strip()

            if is_new:
                existing_content = ""
                change_type = "created"
                modified_content = f"""# New Module: {rel_path}
# Auto-generated by Coder Agent for task: {task_request}

def handle_{rel_path.split('/')[-1].replace('.', '_')}_feature():
    \"\"\"
    Implementation of {task_request}
    \"\"\"
    return {{"status": "active", "task": "{task_request}"}}
"""
            else:
                change_type = "modified"
                comment_marker = "//" if rel_path.endswith((".ts", ".tsx", ".js", ".jsx")) else "#"
                modified_content = existing_content.rstrip() + f"\n\n{comment_marker} AI Developer OS Code Agent: Implemented feature for '{task_request}'\n"

            diff = self.tools.generate_diff(rel_path, existing_content, modified_content)

            # Compute addition and deletion line statistics
            adds = sum(1 for line in diff.splitlines() if line.startswith("+") and not line.startswith("+++"))
            dels = sum(1 for line in diff.splitlines() if line.startswith("-") and not line.startswith("---"))
            total_additions += adds
            total_deletions += dels

            changes.append({
                "file_path": rel_path,
                "change_type": change_type,
                "additions": adds,
                "deletions": dels,
                "old_content": existing_content,
                "new_content": modified_content,
                "diff": diff
            })

        return {
            "status": "success",
            "task_request": task_request,
            "files_modified_count": len(changes),
            "total_additions": total_additions,
            "total_deletions": total_deletions,
            "changes": changes,
            "approval_required": True
        }

    def apply_changes(self, changes: List[Dict[str, Any]]) -> Dict[str, Any]:
        applied_results = []
        for change in changes:
            rel_path = change.get("file_path", "")
            new_content = change.get("new_content", "")
            if rel_path and new_content:
                res = self.tools.apply_diff_to_file(rel_path, new_content)
                applied_results.append({"file_path": rel_path, "status": res})

        return {
            "status": "success",
            "message": f"Successfully applied {len(applied_results)} code changes to workspace.",
            "applied_files": applied_results
        }

