import os
import re
from typing import Dict, Any, List
from agents.coder.tools import CoderTools

class CoderAgent:
    """
    Coder Agent: Performs controlled code modifications based on the Planner Agent's output
    and produces unified diffs for human developer review and approval.
    Includes security guards against path traversal, secret modification, and oversized payloads.
    """

    MAX_FILES_PER_RUN = 5
    MAX_CHANGES_LIMIT = 20
    SENSITIVE_PATTERNS = {
        ".env", ".env.local", ".env.production", ".env.development",
        "id_rsa", "id_ed25519", "credentials.json", "service_account.json",
        "secret.key", "private.key", ".pem", ".pfx", ".pkcs12"
    }

    def __init__(self, root_dir: str):
        self.root_dir = os.path.realpath(os.path.abspath(root_dir))
        self.tools = CoderTools(self.root_dir)

    def _is_safe_path(self, path: str) -> bool:
        if not path or not isinstance(path, str) or "\0" in path:
            return False
        if ".." in path or path.startswith("/") or path.startswith("\\"):
            return False
        base_name = os.path.basename(path).lower()
        if any(pat in base_name for pat in self.SENSITIVE_PATTERNS):
            return False
        return True

    def execute_modification(self, plan: Dict[str, Any]) -> Dict[str, Any]:
        if not plan or not isinstance(plan, dict):
            plan = {}

        raw_task = plan.get("task_request", "Update software functionality")
        task_request = re.sub(r"[\x00-\x1f\x7f-\x9f]", " ", str(raw_task)).strip()[:5000]

        affected_files_detailed = plan.get("affected_files_detailed", [])
        
        if affected_files_detailed and isinstance(affected_files_detailed, list):
            candidate_files = [f.get("path", "") for f in affected_files_detailed if isinstance(f, dict)]
        else:
            candidate_files = plan.get("affected_files", ["apps/web/src/app/login/page.tsx", "apps/api/main.py"])

        target_files = [f for f in candidate_files if self._is_safe_path(f)][:self.MAX_FILES_PER_RUN]
        if not target_files:
            target_files = ["apps/api/main.py"]

        changes = []
        total_additions = 0
        total_deletions = 0

        for rel_path in target_files:
            existing_content = self.tools.read_file(rel_path)
            is_new = existing_content.startswith("Error") or existing_content.startswith("Security Error") or not existing_content.strip()

            if is_new:
                existing_content = ""
                change_type = "created"
                clean_name = rel_path.split('/')[-1].replace('.', '_')
                modified_content = f"""# New Module: {rel_path}
# Auto-generated by Coder Agent for task: {task_request}

def handle_{clean_name}_feature():
    \"\"\"
    Implementation of {task_request}
    \"\"\"
    return {{"status": "active", "task": "{task_request}"}}
"""
            else:
                change_type = "modified"
                comment_marker = "//" if rel_path.endswith((".ts", ".tsx", ".js", ".jsx")) else "#"
                modified_content = existing_content.rstrip() + f"\n\n{comment_marker} AI Developer OS Code Agent: Implemented feature for '{task_request}'\n"

            diff = self.tools.generate_diff(rel_path, existing_content, modified_content)

            # Compute addition and deletion line statistics
            adds = sum(1 for line in diff.splitlines() if line.startswith("+") and not line.startswith("+++"))
            dels = sum(1 for line in diff.splitlines() if line.startswith("-") and not line.startswith("---"))
            total_additions += adds
            total_deletions += dels

            changes.append({
                "file_path": rel_path,
                "change_type": change_type,
                "additions": adds,
                "deletions": dels,
                "old_content": existing_content,
                "new_content": modified_content,
                "diff": diff
            })

        return {
            "status": "success",
            "task_request": task_request,
            "files_modified_count": len(changes),
            "total_additions": total_additions,
            "total_deletions": total_deletions,
            "changes": changes,
            "approval_required": True
        }

    def apply_changes(self, changes: List[Dict[str, Any]]) -> Dict[str, Any]:
        if not changes or not isinstance(changes, list):
            return {
                "status": "error",
                "message": "No valid changes provided to apply.",
                "applied_files": []
            }

        applied_results = []
        for change in changes[:self.MAX_CHANGES_LIMIT]:
            if not isinstance(change, dict):
                continue
            rel_path = change.get("file_path", "")
            new_content = change.get("new_content", "")
            if not self._is_safe_path(rel_path):
                applied_results.append({
                    "file_path": str(rel_path),
                    "status": "Security Error: Path traversal or sensitive file access denied."
                })
                continue

            if rel_path and new_content is not None:
                res = self.tools.apply_diff_to_file(rel_path, str(new_content))
                applied_results.append({"file_path": rel_path, "status": res})

        return {
            "status": "success",
            "message": f"Successfully processed {len(applied_results)} code changes.",
            "applied_files": applied_results
        }


